.buildContainer <- function(dockerhub_tag) {
  buildargs <- paste0("build -t ", dockerhub_tag, " .")
  message("Building container.")
  system2("docker", args = buildargs)
}

.pushToDockerHub <- function(dockerhub_tag) {
  pushargs_hub <- paste0("push ", dockerhub_tag)
  message("Pushing container to Docker Hub.")
  system2("docker", args = pushargs_hub)
}

.pushToGithub <- function(dockerhub_tag, ghcr_tag) {
  tagargs <- paste0("tag ", dockerhub_tag, " ", ghcr_tag)
  system2("docker", args = tagargs)
  pushargs_ghcr <- paste0("push ", ghcr_tag)
  message("Pushing container to GitHub container registry.")
  system2("docker", args = pushargs_ghcr)
}


##' @title Build and Push the Container
##'
##' @description A simple function to build and push the container to Docker Hub
##'     or optionally Github directly from R.
##'
##' @param container `character(1)` with the path to the container directory, as
##'     generated by [makeSimpleBiocContainer()].
##'
##' @param dockerUsername `character(1)` container a Docker Hub username.
##'
##' @param ghUsername `character(1)` container a GitHub username.
##'
##' @return Returns the named vector of the Docker (and optional) GitHub
##'     containers in the registries.
##'
##' @author Ata Badr Barzegar and Laurent Gatto
buildPushDocker <- function(container, dockerUsername, ghUsername = NULL) {
  oldpath <- getwd()
  on.exit(setwd(oldpath))

  image_name <- basename(container)
  dockerhub_tag <- paste0(dockerUsername, "/", image_name)
  setwd(container)

  .buildContainer(dockerhub_tag)
  .pushToDockerHub(dockerhub_tag)

  if (!is.null(ghUsername)) {
    ghcr_tag <- paste0("ghcr.io/", ghUsername, "/", image_name)
    .pushToGithub(dockerhub_tag, ghcr_tag)
  } else {
    ghcr_tag <- NULL
  }

  message("Done.")
  return(c(DockerHub = dockerhub_tag, GHCR = ghcr_tag))
}
